# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_SYNAPTICS_TS_KIT)  += synaptics/
obj-$(CONFIG_PARADE_TS_KIT)  += parade/
obj-$(CONFIG_NOVATEK_TS_KIT)  += novatek/
obj-$(CONFIG_ATMEL_TS_KIT)  += atmel/
obj-$(CONFIG_WACOM_TS_KIT)  += wacom/
