obj-$(CONFIG_HUAWEI_CHARGER)	+= charger/
obj-$(CONFIG_HUAWEI_POWER_MESG_INTERFACE)	+= power_mesg/
obj-$(CONFIG_HUAWEI_KSTATE)	+= hw_kstate/
obj-$(CONFIG_HUAWEI_SMPL)	+= smpl/
obj-$(CONFIG_BUCKBOOST)	+= buckboost/
obj-$(CONFIG_BUCKBOOST)	+= buck_boost/
obj-$(CONFIG_HUAWEI_USB_SHORT_CIRCUIT_PROTECT)	+= usb_short_circuit_protect/
obj-$(CONFIG_HUAWEI_CPU_BUCK)	+= cpu_buck/
obj-$(CONFIG_BOOST_5V)	+= boost_5v/
obj-$(CONFIG_HUAWEI_DSM)	+= power_dsm/
obj-$(CONFIG_HUAWEI_POWER_THERMALZONE)	+= power_thermalzone/
obj-$(CONFIG_HUAWEI_SOC_CONTROL) += hardware_monitor/

obj-$(CONFIG_HUAWEI_WATER_CHECK) += water_check/
obj-$(CONFIG_DOZE_FILTER)	+= wifi_filter/
